### ISSUE TITLE
[Feature request] Define CI + propagate Docker build downstream

### ISSUE THREAD

**Issue by Sinclert** [diana-hep/madminer#449]
This issue describes the request for a GitHub Actions _Continuous Integration_ workflow, in charge of performing basic quality operations, as long as, possibly, the update of _down-stream_ Docker images.

---

### Current situation
Madminer offers a [Travis CI workflow](https://github.com/diana-hep/madminer/blob/master/.travis.yml) to both test and publish the auto-generated Madminer Docker image.

---

### Issue
With the usage of Madminer, and its generated image as base image for other _down-stream_ Docker images (i.e. [madminer-jupyter-env](https://github.com/scailfin/madminer-jupyter-env), [madminer-workflow-ml](https://github.com/scailfin/madminer-workflow-ml) and [madminer-workflow-ph](https://github.com/scailfin/madminer-workflow-ph)) within GitHub repositories, there is space for automatizing the update of those _dependant_ Docker images.

---

### Proposal
We could define a couple of GitHub Actions workflows:

- `ci.yml`: performing code quality operations (pseudo-translation from the Travis CI one), launched upon PR or merge:

    ```yaml
    on:
      push:
        branches:
          - master
      pull_request:
        branches:
          - master
    ```
- `docker.yml` building and pushing the Docker image **as well us triggering down-stream Docker images update** on dependant repositories.

    ```yaml
    on:
      push:
        branches:
          - master
        tags:
          - v*
    ```

---

### Final comments
The reasons for proposing of those CI/CD workflows on _GitHub Actions_, are:
1. Native integration with GitHub.
2. Easier authentication when triggering other workflows (compared to Travis CI).

---

@cranmer now we have an issue to track the proposal we discussed.
